default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: openitstudy_development

test:
  <<: *default
  database: openitstudy_test

production:
  <<: *default
  database: openitstudy_production
  username: openitstudy
  password: <%= ENV['OPENITSTUDY_DATABASE_PASSWORD'] %>
