# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85cd3e2088ff652cbf589f27459479d5410a3ae86c9cf314078006a881cf135126f32b0bf4d3f5e97895825702f755542436e5b9e7dae4c65b1dc4e54555ac22

test:
  secret_key_base: 2f94a4809c385b1788d05295886bc690100f241dc799fcf5d941457987db6c3058b0e766b529403c90e25965bde914872f717c276dfdcae3d3ea6e3e887ee1a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
